package com.insanitybringer.padsim.game.skills;

public class SkillEffect
{
    public final static int Active_MassAttack_AttackMultiplier_Attribute = 0;
    public final static int Active_MassAttack_SetDamage_Attribute = 1;
    public final static int Active_SingleAttack_AttackMultiplier = 2;
    public final static int Active_Shield = 3;
    public final static int Active_Poison = 4;
    public final static int Active_TimeStop = 5;
    public final static int Active_Gravity = 6;
    public final static int Active_Heal_RecoveryMultiplier = 7;
    public final static int Active_Heal_FixedRecovery = 8;
    public final static int Active_ChangeOrbType = 9;
    public final static int Active_RefreshBoard = 10;
    public final static int Leader_AttackBoost_Attribute = 11;
    public final static int Leader_BonusAttack = 12;
    public final static int Leader_Autoheal = 13;
    public final static int Leader_Resolve = 14;
    public final static int Leader_TimeExtend = 15;
    public final static int Leader_Shield = 16;
    public final static int Leader_Shield_VsAttribute = 17;
    public final static int Active_Delay = 18;
    public final static int Active_ReduceDefense = 19;
    public final static int Active_ChangeOrbType_Double = 20;
    public final static int Active_VoidAttributeDamage = 21;
    public final static int Leader_AttackBoost_Type = 22;
    public final static int Leader_HealthBoost_Type = 23;
    public final static int Leader_RecoveryBoost_Type = 24;
    public final static int Skill_25 = 25;
    public final static int Leader_AttackBoost = 26;
    public final static int Skill_27 = 27; //double check
    public final static int Leader_AttackRecoveryBoost = 28;
    public final static int Leader_AllStatBoost = 29;
    public final static int Leader_HealthBoost_DoubleTypes = 30; //strangely specific
    public final static int Leader_AttackBoost_DoubleTypes = 31;
    public final static int Skill_32 = 32;
    public final static int Leader_TaikoSound = 33;
    public final static int Skill_34 = 34;
    public final static int Active_SingleAttack_Drain = 35;
    public final static int Leader_Shield_VsAttribueDouble = 36;
    public final static int Active_SingleAttack_AttackMultiplier_Attribute = 37;
    public final static int Leader_Shield_WhenHPLower = 38;
    public final static int Leader_AttackBoost_WhenHPLower = 39;
    public final static int Leader_AttackBoost_DoubleAttribute = 40;
    public final static int Leader_Counterattack = 41;
    public final static int Active_MassAttack_VsAttribute = 42;
    public final static int Leader_Shield_WhenHPHigher = 43;
    public final static int Leader_AttackBoost_WhenHPHigher = 44;
    public final static int Leader_HealthAttackBoost_Attribute = 45;
    public final static int Leader_HealthBoost_DoubleAttribute = 46;
    public final static int Skill_47 = 47; //GUESS
    public final static int Leader_HealthBoost_Attribute = 48;
    public final static int Leader_RecoveryBoost_Attribute = 49;
    public final static int Active_AttackBoost_Attribute_ = 50; //(also needs double checking? Try skill 1108 =  3 params on skill 1425 =  used by norse skills
    public final static int Active_OnlyMassAttacks = 51;
    public final static int Active_EnhanceOrbType = 52;
    public final static int Leader_EggsBoost = 53;
    public final static int Leader_CoinsBoost = 54;
    public final static int Active_SingleAttack_FixedDamage = 55;
    public final static int Active_MassAttack_FixedDamage = 56;
    public final static int Skill_57 = 57;
    public final static int Active_MassAttack_RandomDamage = 58;
    public final static int Active_SingleAttack_RandomDamage = 59; //(skill 1633)
    public final static int Active_Counterattacks = 60;
    public final static int Leader_AttackBoost_MatchAttributes = 61;
    public final static int Leader_HealthAttackBoost_Type = 62;
    public final static int Leader_HealthRecoveryBoost_Type = 63;
    public final static int Leader_AttackRecoveryBoost_Type = 64;
    public final static int Leader_StatBoost_Type = 65;
    public final static int Leader_AttackBoost_Combos = 66;
    public final static int Leader_HealthRecoveryBoost_Attribute = 67;
    public final static int Skill_68 = 68;
    public final static int Leader_AttackBoost_Attribute_Type = 69;
    public final static int Skill_70 = 70;
    public final static int Active_ChangeBoard = 71;
    public final static int Skill_72 = 72;
    public final static int Leader_HealthAttackBoost_Attribute_Type = 73;
    public final static int Skill_74 = 74;
    public final static int Leader_AttackRecoveryBoost_Attribute_Type = 75;
    public final static int Leader_StatBoost_Attribute_Type = 76;
    public final static int Leader_HealthAttackBoost_DoubleTypes = 77;
    public final static int Skill_78 = 78;
    public final static int Leaders_AttackRecoveryBoost_DoubleTypes = 79;
    public final static int Skill_80 = 80;
    public final static int Skill_81 = 81;
    public final static int Skill_82 = 82;
    public final static int Skill_83 = 83;
    public final static int Active_MassAttack_DamageFromHealth = 84; //check skill 1431 or 1448;
    public final static int Active_SingleAttack_AttackMult_HealthFallsTo1 = 85; //(Overcoming HArdship)
    public final static int Skill_86 = 86;
    public final static int Active_SingleAttack__HealthFallsTo1_ = 87; //(need to compare to 85)
    public final static int Active_AttackBoost_Type = 88; //3 fields? ranodm example 2024 (partial skill)
    public final static int Skill_89 = 89;
    public final static int Active_AttackBoost_Attribute__ = 90; //(actually what) (4 params), skill 1494
    public final static int Active_EnhanceOrbs_Double = 91;
    public final static int Active_AttackBoost_MultiType =  92; //(check skill 1314) =  4 params? Double type?
    public final static int Active_BecomeLeader = 93;
    public final static int Leader_AttackBoost_Attribute_WhenHPLower = 94;
    public final static int Leader_AttackBoost_Type_WhenHPLower = 95;
    public final static int Leader_AttackBoost_Attribute_WhenHPHigher = 96;
    public final static int Leader_AttackBoost_Type_WhenHPHigher = 97;
    public final static int Leader_AttackBoost_Combos_Scaling = 98; //"Moonlit Cat"
    public final static int Skill_99 = 99;
    public final static int Leader_AttackBoost_WhenSkillUsed = 100;
    public final static int Leader_AttackBoost_AtExactCombos = 101;
    public final static int Skill_102 = 102;
    public final static int Leader_AttackRecoveryBoost_Combos = 103; //weird skill
    public final static int Leader_AttackBoost_Attribute_Combos = 104; //"Flame Harmony" =  fairy skills
    public final static int Leader_AttackBoost_RecoveryPenalty = 105;
    public final static int Skill_106 = 106;
    public final static int Skill_107 = 107;
    public final static int Leader_AttackBoost_Attribute_HealthPenalty = 108;
    public final static int Leader_AttackBoost_NumberOfMatchedAttribute = 109;
    public final static int Active_MassAttack_DamageFromHealth_ = 110;
    public final static int Leader_HealthAttackBoost_DoubleAttributes = 111; //(DOUBLE CHECK ME) (skill 885 checks out?)
    public final static int Skill_112 = 112;
    public final static int Skill_113 = 113;
    public final static int Leader_StatBoost_DoubleAttributes = 114;
    public final static int Active_SingleAttack_Drain_ = 115; //"Soul Drain"
    public final static int Active_MultiSkills = 116;
    public final static int Active_HealAndUnbind = 117;
    public final static int Active_UseRandomSkill = 118;
    public final static int Leader_AttackBoost_NumberOfMatchedAttribute_Scaling = 119;
    public final static int Skill_120 = 120;
    public final static int Leader_StatBoost = 121; //Eyes of Heaven, "Secret of the Shrine Maiden's Dance", "Shadowy Proverb" boosts RCV too, usable for types and attributes
    public final static int Leader_AttackBoost_AttributeType_WhenHPLower = 122; //skill 1705 (restricted to some aspect? 4 params) =  "Eight-Headed Dragon's Gaze"
    public final static int Leader_AttackBoost_AttributeType_WhenHPHigher = 123; //"Burning Dragon Power" "Necro soul"
    public final static int Leader_AttackBoost_MatchAttributes_Specific_Scaling = 124; //("Blessed Water Peacock")
    public final static int Leader_StatBoost_WithSpecifiedMonsters = 125;
    public final static int Active_IncreaseSkyfallChance = 126; //see skill 2047;
    public final static int Active_ConvertColumns = 127; //skill 1637. 2063 for double changer.
    public final static int Active_ConvertRows = 128; //skill 1467, 1639 Fire spell
    public final static int Leader_StatBoost_WithShield = 129; //check Protection of Hyperion for details and "Godly Wall of Demonic Ice" =  ""Purgatory Dragon's Divine Magic""
    public final static int Skill_130 = 130;
    public final static int Skill_131 = 131;
    public final static int Active_TimeExtend = 132; //see 2030 or 2060;
    public final static int Skill_133 = 133;
    public final static int Skill_134 = 134;
    public final static int Skill_135 = 135;
    public final static int Leader_StatBoost_Attribute_DoubleBoosts = 136;
    public final static int Leader_StatBoost_Type_DoubleBoosts = 137;
    public final static int Leader_MultiSkills = 138;
    public final static int Leader_AttackBoost_WhenHPGreaterOrLower = 139; //(check skill 875 or 1559 Civilized Tactics)
    public final static int Active_EnhanceOrbs_Multi = 140; //see skill 2092. Bitfield for types?
    public final static int Active_ConvertNOrbs = 141;
    public final static int Active_ChangeAttribute = 142; //skill 2050;
    public final static int Skill_143 = 143;
    public final static int Skill_144 = 144;
    public final static int Skill_145 = 145;
    public final static int Active_Haste = 146;
    public final static int Skill_147 = 147;
    public final static int Leader_ExpBoost = 148;
    public final static int Skill_149 = 149;
    public final static int Skill_150 = 150;
    public final static int Skill_151 = 151;
    public final static int Skill_152 = 152;
    public final static int Skill_153 = 153;
    public final static int Active_ConvertOrbs_3TypesTo1 = 154; //(skill 1416)
    public final static int Skill_155 = 155;
    public final static int Skill_156 = 156;
    public final static int Skill_157 = 157;
    public final static int Leader_StatBoost_MinOrbMatchRequirement = 158;
    public final static int Leader_AttackBoost_NumberOfMatchedAttribute_Scaling_Dupe = 159; //apparently
    public final static int Skill_160 = 160;
    public final static int Skill_161 = 161;
    public final static int Leader_7x6Board = 162;
    public final static int Skill_163 = 163;
    public final static int Skill_164 = 164;
    public final static int Leader_AttackRecoveryBoost_MatchAttributes = 165;
    public final static int Leader_AttackRecoveryBoost_Combos_Scaling = 166;
    public final static int Leader_AttackRecoveryBoost_NumberOfMatchedAttribute = 167;
    public final static int Skill_168 = 168;
    public final static int Leader_AttackBoost_Combos_Shield = 169;
    public final static int Leader_AttackBoost_MatchAttributes_Shield = 170;
    public final static int Leader_AttackBoost_MatchAttributes_Specific_Shield = 171;
    public final static int Skill_172 = 172;
    public final static int Skill_173 = 173;
    public final static int Skill_174 = 174;
    public final static int Skill_175 = 175;
    public final static int Skill_176 = 176;
    public final static int Leader_AttackBoost_LessThanLeft = 177;
    public final static int Leader_StatBoost_4SecMoveTime = 178;
    public final static int Skill_179 = 179;
    public final static int Skill_180 = 180;
    public final static int Skill_181 = 181;
    public final static int Leader_AttackBoost_NumberOfMatchedAttribute_Shield = 182;
    public final static int Leader_AttackBoost_ShieldGreaterRecoveryLower = 183; //what a mouthful
    public final static int Skill_184 = 184;
    public final static int Leader_StatBoost_TimeExtend = 185;
    public final static int Leader_StatBoost_7x6Board = 186;
}